---
# tasks file for vector-role

    - name: Get vector distrib
      get_url:
        url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.x86_64.rpm"
        dest: "./vector-{{ vector_version }}-1.x86_64.rpm"
    - name: Install vector packages
      become: true
      yum:
        name:
          - vector-{{ vector_version }}-1.x86_64.rpm
      notify: start vector service
    - name: Create vector config
      become: true
      template:
        src: vector.toml.j2
        dest: "/etc/vector/vector.toml"
    - name: Configure service Vector
      become: true
      template:
        src: vector.service.j2
        dest: "/etc/systemd/system/vector.service"
      notify: ReStart Vector service
